apiVersion: apps/v1
kind: Deployment
metadata:
  name: rampme-backend
spec:
  template:
    spec:
      containers:
        - name: backend
          image: ghcr.io/rangelovkiril/rampme-backend:prod-20260903120714 # {"$imagepolicy": "rampme:rampme-backend"}
          envFrom:
            - secretRef:
                name: rampme-backend-secret
