apiVersion: v1
kind: Secret
metadata:
    name: rampme-mqtt-secret
    namespace: rampme
type: Opaque
stringData:
    MQTT_URL: ENC[AES256_GCM,data:fUSiSaeQu1IzMYW6lrVFHq3swM90D9RqSknZ,iv:rY+ou7COtt/kGFew9eStdkN/fRSQxwZw78Kq1daq1Mo=,tag:pqv6PhMuD9mmLjkhc4z34w==,type:str]
    MQTT_USERNAME: ENC[AES256_GCM,data:wVgNK91rXh+gOzaN3g4B0fP9cSgfKtJWUalICy2WznJlWfpHfTVLw76ynfC/+Ob71EJL9cdWRJ4mVuKBbpp2zw==,iv:X5S3F3T0Ll/7OeX0OoS1EJfJl2gCCRBHXIedATB1F7g=,tag:Z/K41HXQMSWGH0/kTeLbzQ==,type:str]
    MQTT_PASSWORD: ""
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCMndVRjdiNk5mTER1VHVk
            QThlNlVmQUJmS2NsLzFFQ0l0alF1dzNub3g0CmZHZTZKck1pR0lyN3BPQ0NRY3RF
            ellTTSs3Wk55aHVDU0x2Z2FlNHRyWjAKLS0tIDJuc3I2VzNaQ3J1TExoU0x4ZU1i
            cFVEdHVEMk1jRW01c3VUTGhMUEhMdmcKFJe/gNdfciS8DRdsVQRvbSLUalpxXmRg
            oH3y0kWuY1b/0Ev/ftJpAdyZHZ2VJmRMwwce9R2b0dYRG4MAW4bwZg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1aa4n35h4ptkqpvtre9ees6z82wsevxpr28ctu4dmzszqy9d6kd3sf4mtlr
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-08T23:00:15Z"
    mac: ENC[AES256_GCM,data:fNWOnWus+BHAOdA7t26IcA7xa0qB0SUpFt9ti7ha86ZcZvbnNYo6WWs+1c6cdp3kbyNjhXaaFhhZKhcIsREn/7FkGHJfNcFMJUsWPgfm/QQxc9rimeE4nonU5gr2f+PtkzwLjGYGc72zhGCpMKvomnzhBpt/Bpx/jq/FPAuvzlw=,iv:NAOY0SQIk6R28DM3fnfnTRZ5NO+RrTgykDKx8vLOq6I=,tag:AKqAsK1bpqI8ADcZ7AHWYA==,type:str]
    version: 3.13.3
