apiVersion: apps/v1
kind: Deployment
metadata:
  name: rampme-hw-sim
  namespace: rampme
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: rampme-hw-sim
  template:
    metadata:
      labels:
        app: rampme-hw-sim
    spec:
      containers:
        - name: hw-sim
          image: ghcr.io/rangelovkiril/rampme-hw-sim:stage-20260903202739 # {"$imagepolicy": "rampme:rampme-hw-sim"}
          ports:
            - containerPort: 1883
            - containerPort: 4000
          readinessProbe:
            httpGet:
              path: /health
              port: 4000
            initialDelaySeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 4000
            initialDelaySeconds: 15
