apiVersion: v1
kind: Service
metadata:
  name: hw-sim
  namespace: rampme
spec:
  selector:
    app: hw-sim
  ports:
    - name: mqtt
      port: 1883
      targetPort: 1883
    - name: http
      port: 4000
      targetPort: 4000
