apiVersion: v1
kind: Secret
metadata:
  name: rampme-backend-secret
  namespace: rampme
type: Opaque
stringData:
  MQTT_URL: REPLACE_ME_WITH_MQTT_URL
  MQTT_USERNAME: REPLACE_ME_WITH_MQTT_USERNAME
  MQTT_PASSWORD: REPLACE_ME_WITH_MQTT_PASSWORD
