apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageUpdateAutomation
metadata:
  name: rampme
  namespace: rampme
spec:
  interval: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  git:
    checkout:
      ref:
        branch: main
    commit:
      author:
        email: flux-fleet-app[bot]@users.noreply.github.com
        name: flux-fleet-app
      messageTemplate: |
        chore(rampme): auto-update image tags

        {{ range $resource, $changes := .Changed.Objects -}}
        - {{ $resource.Name }}: {{ range $changes }}{{ .OldValue }} -> {{ .NewValue }}{{ end }}
        {{ end -}}
    push:
      branch: main
  update:
    path: ./apps/rampme
    strategy: Setters
