apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - pvc.yaml
  - imagerepository.yaml
  - imagepolicy.yaml
  - httproute.yaml
patches:
  - path: deployment-patch.yaml
    target:
      kind: Deployment
      name: rampme-backend
  - path: service-patch.yaml
    target:
      kind: Service
      name: rampme-backend
