apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-token
    namespace: cloudflared
type: Opaque
stringData:
    TUNNEL_TOKEN: ENC[AES256_GCM,data:NXtCd1NcqOW3ZDkfhyQ6aS8/BrAbkNO3kEmeeGANVLwLMEnT60H616a+fzh4ZH5oiH60PjcalP1WlekfYPXmPOUJMGrneXbAYzYQhOEtUfcse68QNxdRPNuubgCaqkP5MD96RIj/jAsTDzAQle07eZtO/LnXeg3LU6rG1mT2t2/WQjMad05JYwHM7RPqW1FKGxSbizq8qGK8Oo2Q2iSHc4z7nQB0nir5HxydripmHHBo5EhfIsQn+/OUaRia3eABzuM1V4zqutyiJxay6APhOwxU3LSDe4moBIGRL34TdU8wPvXIno1DDjMAyY0ZbcXX6+tgjFInzZE=,iv:j8dEyEZTaoDAoj44nYUQbGjHD6tsD0F3veAHjcz+86o=,tag:H805vShLoVsdLFMdHqbuOA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByTmI4cjRNKzZxYWs4WjAz
            eWIvMHNhdWJUVGx0U3hCS2ZNejhSZ2wrK3hNCmtOSFZPQ2tIcEVQQXRDUDNmcUhM
            dkc3NERLL2ErS2VyRUtpbDhpeE5kSkUKLS0tIFZuaXhKeVMxNjhySFp3OGhGU1Z3
            OTNCeVhISlJSMEN1SWtzQjdTVXF3bU0K2a0GI+G4C6nulv5XuMi9il7iSHRP6Tfe
            k/seYFqBr48FUB10SdxDApTmKaFYdGUiiMSnxgzv7EWxU98WpbeD1A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1aa4n35h4ptkqpvtre9ees6z82wsevxpr28ctu4dmzszqy9d6kd3sf4mtlr
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-23T20:00:31Z"
    mac: ENC[AES256_GCM,data:uN1i8cyAa+Nge4s3pGoYLMBkUdEp95d5hwyPTpu08oTGGK4wIUAsshiHIHpzouoMLGtJipS+orR5XYf4fblWPuD14SrJ3LXwhJC955iYvKyOWRz/RSyMTShc/kZOASSn5/jeKVVN3dk7elIo4T0OpiyrLXZi/CnZcJk9exw6Fuo=,iv:eU0z/oR817eZwXLckNl6E3OAG/vc0fn+Oz7DetUtT94=,tag:dpiKf3O9h0oDZhb0CUyX9g==,type:str]
    version: 3.13.2
