apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token-secret
    namespace: cert-manager
type: Opaque
stringData:
    api-token: ENC[AES256_GCM,data:CkZFlp/KCn7QLCR5VAk5xG52DtqUn5zGxocE907qDIQSr5TGg50w425NKRGMaGKUp5EhZJ8=,iv:o2IDHsNidHYpABia7qqahO3Sfb45oCXBcJk55YBTQPw=,tag:q6/vlJ2r84JpwgSbBau5eg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwWmc3Tk1zeE9TQWxLcmdx
            dHpaamNseUd2Y0N5WE5JbzR0S0RDaXJEZDJJCjBxLzYyRkxkUWRIR2YveHR3QjFV
            ZXNHOEpoU1J3bkVuRVlWa1pMNTJ6VHMKLS0tIFgvOCtXUUFTdWR2a2dHdC9vZFRy
            Qll5NytVUnlHL3lQbVE0WkpuRlJaOGcKhB/m+ILfa3S3xCwwcDlnNdvYTj+GBigO
            oIS5JJT1zebnMrReuFmFEyHYC7Hd0+xAhRtPQq+HQYG8yB4oWmGryQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1aa4n35h4ptkqpvtre9ees6z82wsevxpr28ctu4dmzszqy9d6kd3sf4mtlr
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-23T17:42:37Z"
    mac: ENC[AES256_GCM,data:762doIEJgrLqIDPZ1wQY+JrXOeq+qkOMbn/tOLT0DhOQ+0rUjPm4Pz+ZiDWLNVTLQIX4UZZwuXJxaMAZvQR5roNGuoQggVEcOIrOancZ3Yhq8pL7MREXR9BqQpj/WE2Q6wiEONFG68lPc9001JJpDwHRJaveGVgUsBJ+vZSz5x8=,iv:a/XwjMdASuSPJ85DS/Mzon2LUV/ud7sdGCw1vlXnLGI=,tag:YD3d5h/BWCKY0HMQvA7zvw==,type:str]
    version: 3.13.2
