apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - imagerepository-backend.yaml
  - imagerepository-frontend.yaml
  - imagepolicy-backend.yaml
  - imagepolicy-frontend.yaml
  - imageupdateautomation.yaml
